### ISSUE TITLE
Please change bugtracker link

### ISSUE THREAD

**Issue by pcav** [brenykurien/bhuvan_web_services#1]
It currently points to the repo, not to the issues page.
Thanks.

**Comment by pcav** [comment]
Also a link for the homepage would be appreciated. If nothing more descriptive is available, a link to this repo would be OK.
Thanks.

**Comment by brenykurien** [comment]
I have made changes as suggested. 
Thanks.

**Comment by pcav** [comment]
thanks
could you please also add the homepage?

**Comment by brenykurien** [comment]
I don't have anything descriptive for homepage, instead added link to this repo.
Hope this is okay.
Thanks.

**Comment by pcav** [comment]
still broken here:
http://plugins.qgis.org/plugins/bhuvan_web_services-master/
